import { GetServerSideProps } from 'next';
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <p className="text-3xl font-bold">Test</p>
      <p className="text-2xl">Hello</p>
     
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const headers = ctx.req.headers;
  console.log(headers)
  return {
    props: {

    }
  }
}
